/**
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EventCallbackPayload
 */
class EventCallbackPayload extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.eventId = this.constructor.getValue(obj.eventId || obj.EventId, '123456789');
        this.eventType = this.constructor.getValue(obj.eventType || obj.EventType, 'QUEUED');
        this.requestId = this.constructor.getValue(obj.requestId || obj.RequestId);
        this.eventData = this.constructor.getValue(obj.eventData || obj.EventData);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'eventId', realName: 'EventId' },
            { name: 'eventType', realName: 'EventType' },
            { name: 'requestId', realName: 'RequestId' },
            { name: 'eventData', realName: 'EventData' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EventCallbackPayload;
