/**
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PartnerAirtimeResponse
 */
class PartnerAirtimeResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.errorCode = this.constructor.getValue(obj.errorCode || obj.ErrorCode, 0);
        this.errorDescription =
          this.constructor.getValue(obj.errorDescription
     || obj.ErrorDescription);
        this.referenceId = this.constructor.getValue(obj.referenceId || obj.ReferenceId);
        this.requestId = this.constructor.getValue(obj.requestId || obj.RequestId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'errorCode', realName: 'ErrorCode' },
            { name: 'errorDescription', realName: 'ErrorDescription' },
            { name: 'referenceId', realName: 'ReferenceId' },
            { name: 'requestId', realName: 'RequestId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = PartnerAirtimeResponse;
