/**
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const servers = require('./Servers');
const environments = require('./Environments');
const apiHelper = require('./APIHelper');

const environmentsMap = [];

environmentsMap[environments.PRODUCTION] = [];
environmentsMap[environments.SANDBOX] = [];
environmentsMap[environments.DEVELOPMENT] = [];

environmentsMap[environments.PRODUCTION][servers.MDEFAULT] =
    'https://api.partner.credofaster.co.ke';
environmentsMap[environments.PRODUCTION][servers.MY_CALLBACK_ENDPOINT] =
    'https://posthere.io/dfd0-4d32-8ad9';
environmentsMap[environments.SANDBOX][servers.MDEFAULT] =
    'https://api-test.partner.credofaster.co.ke';
environmentsMap[environments.SANDBOX][servers.MY_CALLBACK_ENDPOINT] =
    'https://posthere.io/dfd0-4d32-8ad9';
environmentsMap[environments.DEVELOPMENT][servers.MDEFAULT] =
    'https://partner.credofaster.co.ke/crm_api/api/';
environmentsMap[environments.DEVELOPMENT][servers.MY_CALLBACK_ENDPOINT] =
    'https://partner.credofaster.co.ke/crm_api/api/';

const Configuration = {
    // Assigned APIKey
    apiKey: 'XXXX-XXXX-XXXX-XXXX',

    // Assigned ClientId
    clientId: 'ABCDEDFG1234',

    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.SANDBOX,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        const url = environmentsMap[this.currentEnvironment][server || servers.MDEFAULT];
        const urlParams = {
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
