/**
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Environments = {

    /**
     * Live Environment
     */
    PRODUCTION: 'production',

    /**
     * For Test Purpose
     */
    SANDBOX: 'Sandbox',

    /**
     * Development
     */
    DEVELOPMENT: 'Development',

};

module.exports = Environments;
