/**
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const PartnerAirtimeRequest = require('../lib/Models/PartnerAirtimeRequest');
const SingleAirtimeParameter = require('../lib/Models/SingleAirtimeParameter');
const Initiator = require('../lib/Models/Initiator');
const Denomination = require('../lib/Models/Denomination');
const PartnerAirtimeResponse = require('../lib/Models/PartnerAirtimeResponse');
const PartnerAirtimeBalanceResponse = require('../lib/Models/PartnerAirtimeBalanceResponse');
const RegisterCallbackRequest = require('../lib/Models/RegisterCallbackRequest');
const EventCallbackPayload = require('../lib/Models/EventCallbackPayload');
const RegisterCallbackResponse = require('../lib/Models/RegisterCallbackResponse');
const EventCallbackFeedback = require('../lib/Models/EventCallbackFeedback');

const classMap = {
    PartnerAirtimeRequest,
    SingleAirtimeParameter,
    Initiator,
    Denomination,
    PartnerAirtimeResponse,
    PartnerAirtimeBalanceResponse,
    RegisterCallbackRequest,
    EventCallbackPayload,
    RegisterCallbackResponse,
    EventCallbackFeedback,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
